name: E2E Adapter Healthcheck

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Start adapter container
        run: |
          set -e
          OWNER="${{ github.repository_owner }}"
          OWNER="$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')"
          IMAGE="ghcr.io/${OWNER}/corealpha-adapter:latest"
          docker pull "$IMAGE"
          docker run -d --rm --name ca-adapter -p 8000:8000 "$IMAGE"
          echo "Waiting for /healthz ..."
          for i in $(seq 1 40); do
            code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/healthz || true)
            if [ "$code" = "200" ]; then
              echo "OK: /healthz returned 200"; exit 0
            fi
            sleep 2
          done
          echo "ERROR: /healthz did not return 200 in time"
          docker logs ca-adapter || true
          exit 1

      - name: Dump logs on failure
        if: failure()
        run: docker logs ca-adapter || true

      - name: Stop container
        if: always()
        run: docker stop ca-adapter || true
